# Generated by Django 4.2.5 on 2023-09-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_item_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='rarity',
            field=models.CharField(choices=[('Common', 'Common'), ('Uncommon', 'Common'), ('Rare', 'Rare'), ('Very rare', 'Very rare'), ('Epic', 'Epic'), ('Legendary', 'Legendary')], max_length=9),
        ),
    ]
